name: jiant

dependencies:
    - python=3.6
    - pytorch=0.4
    - numpy=1.14.2
    - nltk=3.2.5
    - scikit-learn=0.19.1
    - pip:
        - allennlp==0.4
        - ipdb
        - tensorboard
        - tensorboardX=1.2
